%% Init

close all
clearvars -except annulation month2year years entry
clc


%% Load: smart method

global annulation years entry

if isempty(annulation)
    load annulations_data.mat
end

if isempty(entry)
    load entry_data.mat
end

table.annulation = annulation;
table.entry = entry;


%% General parameters

timeVect = 1:size(table.annulation.allMonths.str,1);

LineStyle.m10 = '-';
LineStyle.auto = '-';
LineStyle.p10 = ':';

Marker.m10 = 'none';
Marker.auto = 'none';
Marker.p10 = 'none';

Color.m10 = [1 0 0];
Color.auto = [0 0 1];
Color.p10 = [0 0.7 0];

LineWidth = 2;


%% per Month

f1 = figure(...
    'Name'        ,'Annul details',...
    'NumberTitle' ,'off'                       ,...
    'Units'       , 'Normalized'               ,...
    'Position'    , [0.05, 0.05, 0.90, 0.80]    ...
    );

ax1 = zeros(3,1);
ax1(1) = subplot(3,1,1);
ax1(2) = subplot(3,1,2);
ax1(3) = subplot(3,1,3);

axes(ax1(1))
hold all
% m10
plot(ax1(1),...
    timeVect,sum(table.annulation.perMonth.m10,2),... % Prisma + Verio
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','m10');
% auto
plot(ax1(1),...
    timeVect,sum(table.annulation.perMonth.auto,2),... % Prisma + Verio
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','auto');
% p10
plot(ax1(1),...
    timeVect,sum(table.annulation.perMonth.p10,2),... % Prisma + Verio
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','p10');
ylabel('Prisma + Verio')

axes(ax1(2))
hold all
plot(ax1(2),...
    timeVect,table.annulation.perMonth.m10(:,1),... % Prisma
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','m10');
plot(ax1(2),...
    timeVect,table.annulation.perMonth.auto(:,1),... % Prisma
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','auto');
plot(ax1(2),...
    timeVect,table.annulation.perMonth.p10(:,1),... % Prisma
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','p10');
ylabel('Prisma')

axes(ax1(3))
hold all
plot(ax1(3),...
    timeVect,table.annulation.perMonth.m10(:,2),... % Verio
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','- 10j');
plot(ax1(3),...
    timeVect,table.annulation.perMonth.auto(:,2),... % Verio
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','= 10j (auto)');
plot(ax1(3),...
    timeVect,table.annulation.perMonth.p10(:,2),... % Verio
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','+ 10j');
ylabel('Verio')


% Adjustements

% legend(ax(1),'Location','NorthWest')
% legend(ax(2),'Location','NorthWest')
legend(ax1(3),'Location','NorthWest')

set(ax1(:),'XTick',1:12:timeVect(end))
set(ax1(:),'XTickLabel',num2str(years))
set(ax1(:),...
    'XGrid','on',...
    'YGrid','on',...
    'XMinorGrid','off',...
    'YMinorGrid','off',...
    'GridLineStyle',':')

axis(ax1(:),'tight')
ylim(ax1(2),[0 56])
ylim(ax1(3),[0 56])

linkaxes(ax1,'x')


%% per Year

year.total = nan(length(years),2);
year.m10 = nan(length(years),2);
year.auto = nan(length(years),2);
year.p10 = nan(length(years),2);

for y = 1 : length(years)
    
    year.total(y,:) = nansum(table.annulation.perYears.(sprintf('y%d',years(y))).total,1);
    year.m10(y,:) = nansum(table.annulation.perYears.(sprintf('y%d',years(y))).m10,1);
    year.auto(y,:) = nansum(table.annulation.perYears.(sprintf('y%d',years(y))).auto,1);
    year.p10(y,:) = nansum(table.annulation.perYears.(sprintf('y%d',years(y))).p10,1);
    
end

timeVectYEARS = 1 : length(years);

f2 = figure(...
    'Name'        ,'Annul details',...
    'NumberTitle' ,'off'                       ,...
    'Units'       , 'Normalized'               ,...
    'Position'    , [0.05, 0.05, 0.90, 0.80]    ...
    );

ax2 = zeros(3,1);
ax2(1) = subplot(3,1,1);
ax2(2) = subplot(3,1,2);
ax2(3) = subplot(3,1,3);

axes(ax2(1))
hold all
% m10
plot(ax2(1),...
    timeVectYEARS,sum(year.m10,2),... % Prisma + Verio
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','m10');
% auto
plot(ax2(1),...
    timeVectYEARS,sum(year.auto,2),... % Prisma + Verio
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','auto');
% p10
plot(ax2(1),...
    timeVectYEARS,sum(year.p10,2),... % Prisma + Verio
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','p10');
ylabel('Prisma + Verio')

axes(ax2(2))
hold all
plot(ax2(2),...
    timeVectYEARS,year.m10(:,1),... % Prisma
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','m10');
plot(ax2(2),...
    timeVectYEARS,year.auto(:,1),... % Prisma
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','auto');
plot(ax2(2),...
    timeVectYEARS,year.p10(:,1),... % Prisma
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','p10');
ylabel('Prisma')

axes(ax2(3))
hold all
plot(ax2(3),...
    timeVectYEARS,year.m10(:,2),... % Verio
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','- 10j');
plot(ax2(3),...
    timeVectYEARS,year.auto(:,2),... % Verio
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','= 10j (auto)');
plot(ax2(3),...
    timeVectYEARS,year.p10(:,2),... % Verio
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','+ 10j');
ylabel('Verio')


% Adjustements

% legend(ax(1),'Location','NorthWest')
% legend(ax(2),'Location','NorthWest')
legend(ax2(3),'Location','NorthWest')

set(ax2(:),'XTick',1:timeVectYEARS(end))
set(ax2(:),'XTickLabel',num2str(years))
set(ax2(:),...
    'XGrid','on',...
    'YGrid','on',...
    'XMinorGrid','off',...
    'YMinorGrid','off',...
    'GridLineStyle',':')

axis(ax2(:),'tight')
ylim(ax2(2),[0 355])
ylim(ax2(3),[0 355])

linkaxes(ax2,'x')

