%% Init

close all
clearvars -except annulation month2year years entry
clc


%% Load: smart method

global annulation years entry

if isempty(annulation)
    load annulations_data.mat
end

if isempty(entry)
    load entry_data.mat
end

table.annulation = annulation;
table.entry = entry;


%% General parameters

timeVect = 1:size(table.annulation.allMonths.str,1);

LineStyle.m10 = '-';
LineStyle.auto = '-';
LineStyle.p10 = ':';

Marker.m10 = 'none';
Marker.auto = 'none';
Marker.p10 = 'none';

Color.m10 = [1 0 0];
Color.auto = [0 0 1];
Color.p10 = [0 0.7 0];

LineWidth = 2;


%% Scan vs. annul

figure(...
    'Name'        ,'Annul details',...
    'NumberTitle' ,'off'                       ,...
    'Units'       , 'Normalized'               ,...
    'Position'    , [0.05, 0.05, 0.90, 0.80]    ...
    )

ax = zeros(3,1);
ax(1) = subplot(3,1,1);
ax(2) = subplot(3,1,2);
ax(3) = subplot(3,1,3);

axes(ax(1))
hold all
% m10
plot(ax(1),...
    timeVect,sum(table.annulation.perMonth.m10,2),... % Prisma + Verio
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','m10');
% auto
plot(ax(1),...
    timeVect,sum(table.annulation.perMonth.auto,2),... % Prisma + Verio
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','auto');
% p10
plot(ax(1),...
    timeVect,sum(table.annulation.perMonth.p10,2),... % Prisma + Verio
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','p10');
ylabel('Prisma + Verio')

axes(ax(2))
hold all
plot(ax(2),...
    timeVect,table.annulation.perMonth.m10(:,1),... % Prisma
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','m10');
plot(ax(2),...
    timeVect,table.annulation.perMonth.auto(:,1),... % Prisma
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','auto');
plot(ax(2),...
    timeVect,table.annulation.perMonth.p10(:,1),... % Prisma
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','p10');
ylabel('Prisma')

axes(ax(3))
hold all
plot(ax(3),...
    timeVect,table.annulation.perMonth.m10(:,2),... % Verio
    'LineStyle',LineStyle.m10,...
    'Marker',Marker.m10,...
    'Color',Color.m10,...
    'LineWidth',LineWidth,...
    'DisplayName','- 10j');
plot(ax(3),...
    timeVect,table.annulation.perMonth.auto(:,2),... % Verio
    'LineStyle',LineStyle.auto,...
    'Marker',Marker.auto,...
    'Color',Color.auto,...
    'LineWidth',LineWidth,...
    'DisplayName','= 10j (auto)');
plot(ax(3),...
    timeVect,table.annulation.perMonth.p10(:,2),... % Verio
    'LineStyle',LineStyle.p10,...
    'Marker',Marker.p10,...
    'Color',Color.p10,...
    'LineWidth',LineWidth,...
    'DisplayName','+ 10j');
ylabel('Verio')


% Adjustements

% legend(ax(1),'Location','NorthWest')
% legend(ax(2),'Location','NorthWest')
legend(ax(3),'Location','NorthWest')

set(ax(:),'XTick',1:12:timeVect(end))
set(ax(:),'XTickLabel',num2str(years))
set(ax(:),...
    'XGrid','on',...
    'YGrid','on',...
    'XMinorGrid','off',...
    'YMinorGrid','off',...
    'GridLineStyle',':')

axis(ax(:),'tight')
ylim(ax(2),[0 56])
ylim(ax(3),[0 56])

linkaxes(ax,'x')

