%% Init

close all
clearvars -except annulation month2year years entry
clc


%% Load: smart method

global annulation years entry

if isempty(annulation)
    load annulations_data.mat
end

if isempty(entry)
    load entry_data.mat
end

table.annulation = annulation;
table.entry = entry;


%% General parameters

timeVect = 1:size(table.annulation.allMonths.str,1);

LineStyle.entry = '-';
LineStyle.annulation = '-';
LineStyle.ratio = ':';

Marker.entry = 'none';
Marker.annulation = 'none';
Marker.ratio = 'x';

% LineStyle.total = ':';
% LineStyle.m10 = ':';
% LineStyle.auto = ':';
% LineStyle.p10 = ':';

Color.entry = [0 0 1];
Color.annulation = [0 0.7 0];
Color.ratio = [1 0 0];

LineWidth = 2;


%% Scan vs. annul

figure(...
    'Name'        ,'Scan vs. Annul',...
    'NumberTitle' ,'off'                       ,...
    'Units'       , 'Normalized'               ,...
    'Position'    , [0.05, 0.05, 0.90, 0.80]    ...
    )

ax = zeros(3,1);
ax(1) = subplot(3,1,1);
ax(2) = subplot(3,1,2);
ax(3) = subplot(3,1,3);

axes(ax(1))
hold all
% SCAN
plot(ax(1),...
    timeVect,sum(table.entry.perMonth.total,2),... % Prisma + Verio
    'LineStyle',LineStyle.entry,...
    'Marker',Marker.entry,...
    'Color',Color.entry,...
    'LineWidth',LineWidth,...
    'DisplayName','SCAN');
% ANNUL
plot(ax(1),...
    timeVect,sum(table.annulation.perMonth.m10,2)+sum(table.annulation.perMonth.auto,2),... % Prisma + Verio
    'LineStyle',LineStyle.annulation,...
    'Marker',Marker.annulation,...
    'Color',Color.annulation,...
    'LineWidth',LineWidth,...
    'DisplayName','ANNUL');
% RATIO
ratioPV = 100*(sum(table.annulation.perMonth.m10,2)+sum(table.annulation.perMonth.auto,2))./...
    (sum(table.entry.perMonth.total,2) + sum(table.annulation.perMonth.m10,2)+sum(table.annulation.perMonth.auto,2));
plot(ax(1),...
    timeVect,ratioPV,... % Prisma + Verio
    'LineStyle',LineStyle.ratio,...
    'Marker',Marker.ratio,...
    'Color',Color.ratio,...
    'LineWidth',LineWidth,...
    'DisplayName','RATIO');
ylabel('Prisma + Verio')

axes(ax(2))
hold all
plot(ax(2),...
    timeVect,table.entry.perMonth.total(:,1),... % Prisma
    'LineStyle',LineStyle.entry,...
    'Marker',Marker.entry,...
    'Color',Color.entry,...
    'LineWidth',LineWidth,...
    'DisplayName','SCAN');
plot(ax(2),...
    timeVect,table.annulation.perMonth.m10(:,1)+table.annulation.perMonth.auto(:,1),... % Prisma
    'LineStyle',LineStyle.annulation,...
    'Marker',Marker.annulation,...
    'Color',Color.annulation,...
    'LineWidth',LineWidth,...
    'DisplayName','ANNUL');
ratioP = 100*(table.annulation.perMonth.m10(:,1)+table.annulation.perMonth.auto(:,1))./...
    (table.entry.perMonth.total(:,1) + table.annulation.perMonth.m10(:,1)+table.annulation.perMonth.auto(:,1));
plot(ax(2),...
    timeVect,ratioP,... % Prisma + Verio
    'LineStyle',LineStyle.ratio,...
    'Marker',Marker.ratio,...
    'Color',Color.ratio,...
    'LineWidth',LineWidth,...
    'DisplayName','RATIO');
ylabel('Prisma')

axes(ax(3))
hold all
plot(ax(3),...
    timeVect,table.entry.perMonth.total(:,2),... % Verio
    'LineStyle',LineStyle.entry,...
    'Marker',Marker.entry,...
    'Color',Color.entry,...
    'LineWidth',LineWidth,...
    'DisplayName','SCAN');
plot(ax(3),...
    timeVect,table.annulation.perMonth.m10(:,2)+table.annulation.perMonth.auto(:,2),... % Verio
    'LineStyle',LineStyle.annulation,...
    'Marker',Marker.annulation,...
    'Color',Color.annulation,...
    'LineWidth',LineWidth,...
    'DisplayName','ANNUL');
ratioV = 100*(table.annulation.perMonth.m10(:,2)+table.annulation.perMonth.auto(:,2))./...
    (table.entry.perMonth.total(:,2) + table.annulation.perMonth.m10(:,2)+table.annulation.perMonth.auto(:,2));
plot(ax(3),...
    timeVect,ratioV,... % Prisma + Verio
    'LineStyle',LineStyle.ratio,...
    'Marker',Marker.ratio,...
    'Color',Color.ratio,...
    'LineWidth',LineWidth,...
    'DisplayName','RATIO');
ylabel('Verio')


% Adjustements

% legend(ax(1),'Location','NorthWest')
% legend(ax(2),'Location','NorthWest')
legend(ax(3),'Location','NorthWest')

set(ax(:),'XTick',1:12:timeVect(end))
set(ax(:),'XTickLabel',num2str(years))
set(ax(:),...
    'XGrid','on',...
    'YGrid','on',...
    'XMinorGrid','off',...
    'YMinorGrid','off',...
    'GridLineStyle',':')

axis(ax(:),'tight')

linkaxes(ax,'x')

